version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    scope: "@navikt"
    token: ${{ secrets.READER_TOKEN }}
updates:
  - package-ecosystem: npm
    directories:
      - /
      - /aksel.nav.no
      - /aksel.nav.no/*
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    registries:
      - npm-github
    groups:
      sanity:
        group-by: dependency-name
        patterns:
          - "sanity"
          - "sanity-*"
          - "@sanity/*"
          - "next-sanity"
          - "@portabletext/*"
      eslint:
        group-by: dependency-name
        patterns:
          - "eslint"
          - "@eslint/*"
      react:
        group-by: dependency-name
        patterns:
          - "react"
          - "react-dom"
      storybook:
        group-by: dependency-name
        patterns:
          - "*storybook*"
      vitest:
        group-by: dependency-name
        patterns:
          - "vitest"
          - "@vitest/*"
      workspace:
        group-by: dependency-name
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
    registries:
      - npm-github
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directories:
      - "/aksel.nav.no"
      - "/mcp-server"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
