name: "Setup Project"
description: "Checks out repo, sets up Node, installs dependencies and runs boot command."
inputs:
  npm_auth_token:
    description: "NPM Auth Token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: yarn
        cache-dependency-path: "**/yarn.lock"

    - name: Install dependencies
      run: yarn --immutable
      shell: bash
      env:
        NPM_AUTH_TOKEN: ${{ inputs.npm_auth_token }}

    - name: Boot (build packages)
      run: yarn boot
      shell: bash
