name: Train
category: Transportation
sub_category: Public transport
keywords:
  - transport
  - reise
  - bevegelse
  - hastighet
  - kommunikasjon
  - transport
  - travel
  - movement
  - speed
  - communication
variant: Stroke
updated_at: 19.08.2023
created_at: 07.03.2023
