/* prettier-ignore-start */

/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as MinsideImport } from "./routes/minside";
import { Route as SykepengerImport } from "./routes/sykepenger";

// Create/Update Routes

const SykepengerRoute = SykepengerImport.update({
  path: "/sykepenger",
  getParentRoute: () => rootRoute,
} as any);

const MinsideRoute = MinsideImport.update({
  path: "/minside",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/minside": {
      id: "/minside";
      path: "/minside";
      fullPath: "/minside";
      preLoaderRoute: typeof MinsideImport;
      parentRoute: typeof rootRoute;
    };
    "/sykepenger": {
      id: "/sykepenger";
      path: "/sykepenger";
      fullPath: "/sykepenger";
      preLoaderRoute: typeof SykepengerImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/minside": typeof MinsideRoute;
  "/sykepenger": typeof SykepengerRoute;
}

export interface FileRoutesByTo {
  "/minside": typeof MinsideRoute;
  "/sykepenger": typeof SykepengerRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/minside": typeof MinsideRoute;
  "/sykepenger": typeof SykepengerRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/minside" | "/sykepenger";
  fileRoutesByTo: FileRoutesByTo;
  to: "/minside" | "/sykepenger";
  id: "__root__" | "/minside" | "/sykepenger";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  MinsideRoute: typeof MinsideRoute;
  SykepengerRoute: typeof SykepengerRoute;
}

const rootRouteChildren: RootRouteChildren = {
  MinsideRoute: MinsideRoute,
  SykepengerRoute: SykepengerRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/minside",
        "/sykepenger"
      ]
    },
    "/minside": {
      "filePath": "minside.tsx"
    },
    "/sykepenger": {
      "filePath": "sykepenger.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
