#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageJsonPath = path.join(__dirname, "..", "package.json");
const versionFilePath = path.join(__dirname, "..", "src", "version.ts");

const pkg = JSON.parse(fs.readFileSync(packageJsonPath, "utf-8"));

const content = `// Auto-generated by build script - do not edit manually
export const VERSION = "${pkg.version}";
`;

fs.writeFileSync(versionFilePath, content);
console.log(`Generated version.ts with version ${pkg.version}`);
