name: Eksempel p친 bruk
description: Send et eksempel p친 ting fra Aksel som er brukt i det fri (tokens, komponenter, maler, etc)
title: "[Eksempel p친 bruk]: "
labels: ["dokumentasjon 游닀"]
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar til Aksel!
  - type: input
    id: title
    attributes:
      label: Lenke til side
      description: Lenke til siden hvor eksemplet er
      placeholder:
    validations:
      required: true
  - type: textarea
    id: examples
    attributes:
      label: Forklaring
      description: Forklar om det er noe man m친 gj칮re for 친 se eksemplet, eller hvor p친 siden det ligger
