name: Innspill til komponent
description: Send inn innspill til komponent
title: "[Innspill til komponent]: "
labels: ["forespørsel 🥰", "komponenter 🧩", "nytt ✨", "beta 🧪"]
assignees:
  - KenAJoh
body:
  - type: markdown
    attributes:
      value: |
        Takk for at du bidrar inn i Aksel!
  - type: textarea
    id: feeback
    attributes:
      label: Tilbakemelding
      description: Beskriv hvilke tilbakemeldinger du har til komponenten
