import fg from "fast-glob";
import { readFileSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import type { ComponentMetadata } from "../../src/utils/types/metadata";
import { META_GLOB, generatedComponentNamesPath, packageRoot } from "./paths";

/** Extracts "name"-key from metadata export in each *.meta.ts file */
async function readMetaNames(): Promise<string[]> {
  const files = fg.sync(META_GLOB, { cwd: packageRoot, absolute: true });
  const names = await Promise.all(
    files.map(async (file) => {
      // @ts-expect-error Benchmark helper: dynamic import in this script target.
      const { metadata } = (await import(pathToFileURL(file).href)) as {
        metadata?: ComponentMetadata;
      };
      return metadata?.name;
    }),
  );

  return names.filter((name): name is string => typeof name === "string");
}

/**
 * Writes the generated `ComponentName` union, only touching the file when its
 * contents change. Returns `true` when the file was rewritten.
 */
async function writeComponentNames(names?: string[]): Promise<boolean> {
  if (!names) {
    names = await readMetaNames();
  }

  /** Builds the contents of the generated `ComponentName` union module. */
  const unique = Array.from(new Set(names)).sort((a, b) => a.localeCompare(b));
  const body = unique.map((name) => `  | "${name}"`).join("\n");
  const content = `/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Union of every \`name\` declared in a \`*.meta.ts\` file. Regenerated by
 * \`scripts/extract-component-names.ts\`
 */
export type ComponentName =
${body};
`;

  let existing: string | undefined;
  try {
    existing = readFileSync(generatedComponentNamesPath, "utf-8");
  } catch {
    existing = undefined;
  }

  const changed = existing !== content;
  if (changed) {
    writeFileSync(generatedComponentNamesPath, content);
  }
  return changed;
}

export { readMetaNames, writeComponentNames };
