import fg from "fast-glob";
import { readFileSync, statSync, writeFileSync } from "node:fs";
import { pathToFileURL } from "node:url";
import type { ComponentMetadata } from "../../src/utils/types/metadata";
import { META_GLOB, generatedComponentNamesPath, packageRoot } from "./paths";

/** True when meta files changed/were deleted after componentNames was written */
function metaFilesChanged(files: string[]): boolean {
  let componentNames: string;
  let componentNamesMtime: number;
  try {
    const stat = statSync(generatedComponentNamesPath);
    componentNamesMtime = stat.mtimeMs;
    componentNames = readFileSync(generatedComponentNamesPath, "utf-8");
  } catch {
    return true;
  }

  // A deletion leaves no newer mtime, so compare counts to catch it.
  const generatedCount = (componentNames.match(/^\s*\| "/gm) ?? []).length;
  if (generatedCount !== files.length) {
    return true;
  }

  return files.some((file) => statSync(file).mtimeMs > componentNamesMtime);
}

/** Extracts "name"-key from metadata export in each *.meta.ts file */
async function readMetaNames(files: string[]): Promise<string[]> {
  const names = await Promise.all(
    files.map(async (file) => {
      // @ts-expect-error Benchmark helper: dynamic import in this script target.
      const { metadata } = (await import(pathToFileURL(file).href)) as {
        metadata?: ComponentMetadata;
      };
      return metadata?.name;
    }),
  );

  return names.filter((name): name is string => typeof name === "string");
}

/**
 * Writes the generated `ComponentName` union.
 * @returns whether the file was changed.
 */
async function writeComponentNames(names?: string[]): Promise<boolean> {
  if (!names) {
    const files = fg.sync(META_GLOB, { cwd: packageRoot, absolute: true });
    if (!metaFilesChanged(files)) {
      return false;
    }
    names = await readMetaNames(files);
  }

  /** Builds the contents of the generated `ComponentName` union module. */
  const unique = Array.from(new Set(names)).sort((a, b) => a.localeCompare(b));
  const body = unique.map((name) => `  | "${name}"`).join("\n");
  const content = `/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Union of every \`name\` declared in a \`*.meta.ts\` file. Regenerated by
 * \`scripts/extract-component-names.ts\`
 */
export type ComponentName =
${body};
`;

  let existing: string | undefined;
  try {
    existing = readFileSync(generatedComponentNamesPath, "utf-8");
  } catch {
    existing = undefined;
  }

  writeFileSync(generatedComponentNamesPath, content);
  const changed = existing !== content;
  return changed;
}

export { readMetaNames, writeComponentNames };
