import fg from "fast-glob";
import { readFileSync, writeFileSync } from "node:fs";
import { META_GLOB, generatedComponentNamesPath, packageRoot } from "./paths";

/** Matches the `name: "..."` field of a meta file (ignores `displayName`). */
const NAME_PATTERN = /\bname\s*:\s*["'`]([^"'`]+)["'`]/;

/**
 * Reads the `name` of every meta file via a lightweight regex. Intentionally
 * avoids building a TypeScript program so it stays fast and resilient to
 * in-progress type errors (it runs before type-checking/building).
 */
function readMetaNames(): string[] {
  const files = fg.sync(META_GLOB, { cwd: packageRoot, absolute: true });
  const names: string[] = [];
  for (const file of files) {
    const match = readFileSync(file, "utf-8").match(NAME_PATTERN);
    if (match) {
      names.push(match[1]);
    }
  }
  return names;
}

/** Builds the contents of the generated `ComponentName` union module. */
function buildComponentNamesModule(names: string[]): string {
  const unique = Array.from(new Set(names)).sort((a, b) => a.localeCompare(b));
  const body = unique.map((name) => `  | "${name}"`).join("\n");
  return `/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Union of every \`name\` declared in a \`*.meta.ts\` file. Regenerated by
 * \`scripts/extract-component-names.ts\`
 */
export type ComponentName =
${body};
`;
}

/**
 * Writes the generated `ComponentName` union, only touching the file when its
 * contents change. Returns `true` when the file was rewritten.
 */
function writeComponentNames(names: string[] = readMetaNames()): boolean {
  const content = buildComponentNamesModule(names);

  let existing: string | undefined;
  try {
    existing = readFileSync(generatedComponentNamesPath, "utf-8");
  } catch {
    existing = undefined;
  }

  const changed = existing !== content;
  if (changed) {
    writeFileSync(generatedComponentNamesPath, content);
  }
  return changed;
}

export { readMetaNames, buildComponentNamesModule, writeComponentNames };
