apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: verktoykasse
  namespace: designsystem
  labels:
    team: designsystem
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://aksel.dev.nav.no"
    - "https://aksel.ekstern.dev.nav.no"
  liveness:
    path: /api/isAlive
    initialDelay: 10
  readiness:
    path: /api/isAlive
    initialDelay: 10

  resources:
    limits:
      cpu: 2000m
      memory: 2048Mi
    requests:
      cpu: 500m
      memory: 1024Mi

  accessPolicy:
    outbound:
      external:
        - host: api.sanity.io
        - host: hnbe3yhs.api.sanity.io
        - host: apicdn.sanity.io
        - host: hnbe3yhs.apicdn.sanity.io
        - host: cdn.sanity.io
      rules: []
      env:
