apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: verktoykasse
  namespace: designsystem
  labels:
    team: designsystem
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://aksel.ekstern.dev.nav.no"
  liveness:
    path: /api/isAlive
    initialDelay: 10
  readiness:
    path: /api/isAlive
    initialDelay: 10

  accessPolicy:
    outbound:
      external:
        - host: api.sanity.io
        - host: hnbe3yhs.api.sanity.io
        - host: apicdn.sanity.io
        - host: hnbe3yhs.apicdn.sanity.io
        - host: cdn.sanity.io
      rules: []
      env:
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/aksel.nav.no/website/.next/cache