apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: verktoykasse
  namespace: designsystem
  labels:
    team: designsystem
spec:
  envFrom:
    - secret: aksel-website-secrets-dev
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://aksel.ansatt.dev.nav.no"
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  liveness:
    path: /api/isAlive
  readiness:
    path: /api/isAlive

  accessPolicy:
    outbound:
      external:
        - host: api.sanity.io
        - host: api.slack.com
        - host: slack.com
        - host: wss-primary.slack.com
        - host: hnbe3yhs.api.sanity.io
        - host: apicdn.sanity.io
        - host: hnbe3yhs.apicdn.sanity.io
        - host: cdn.sanity.io
        - host: umami.nav.no
        - host: raw.githubusercontent.com
      rules: []
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/aksel.nav.no/website/.next/cache
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  azure:
    application:
      enabled: true
      tenant: nav.no
      allowAllUsers: true
    sidecar:
      enabled: true