export const ACTIVE_MODIFIER_CHANGE = 'ACTIVE_MODIFIER_CHANGE';
export const ACTIVE_MULTIPLE_CHOICE_MODIFIER_CHANGE = 'ACTIVE_MULTIPLE_CHOICE_MODIFIER_CHANGE';
export const ACTIVE_TYPE_CHANGE = 'ACTIVE_TYPE_CHANGE';
export const ACTIVE_REF_CHANGE = 'ACTIVE_REF_CHANGE';
export const BG_COLOR_CHANGE = 'BG_COLOR_CHANGE';