export const ACTIVE_MODIFIER_CHANGE = 'ACTIVE_MODIFIER_CHANGE';
export const ACTIVE_MULTIPLE_CHOICE_MODIFIER_CHANGE = 'ACTIVE_MULTIPLE_CHOICE_MODIFIER_CHANGE';
export const ACTIVE_COMPONENT_CHANGE = 'ACTIVE_COMPONENT_CHANGE';
