export const ACTIVE_MODIFIER_CHANGE = 'ACTIVE_MODIFIER_CHANGE';
export const ACTIVE_MULTIPLE_CHOICE_MODIFIER_CHANGE = 'ACTIVE_MULTIPLE_CHOICE_MODIFIER_CHANGE';
export const ACTIVE_TYPE_CHANGE = 'ACTIVE_TYPE_CHANGE';
