import { getFrameworkRegexes } from "./token-regex";
import { generateBgTwTags, generateRoundedTwTags } from "./token.utils";

const colors = [
  "meta-lime-400A",
  "meta-lime-300A",
  "meta-lime-200A",
  "meta-lime-100A",
  "meta-lime-1000",
  "meta-lime-900",
  "meta-lime-800",
  "meta-lime-700",
  "meta-lime-600",
  "meta-lime-500",
  "meta-lime-400",
  "meta-lime-300",
  "meta-lime-200",
  "meta-lime-100",
  "meta-purple-400A",
  "meta-purple-300A",
  "meta-purple-200A",
  "meta-purple-100A",
  "meta-purple-1000",
  "meta-purple-900",
  "meta-purple-800",
  "meta-purple-700",
  "meta-purple-600",
  "meta-purple-500",
  "meta-purple-400",
  "meta-purple-300",
  "meta-purple-200",
  "meta-purple-100",
  "brand-blue-400A",
  "brand-blue-300A",
  "brand-blue-200A",
  "brand-blue-100A",
  "brand-blue-1000",
  "brand-blue-900",
  "brand-blue-800",
  "brand-blue-700",
  "brand-blue-600",
  "brand-blue-500",
  "brand-blue-400",
  "brand-blue-300",
  "brand-blue-200",
  "brand-blue-100",
  "brand-beige-400A",
  "brand-beige-300A",
  "brand-beige-200A",
  "brand-beige-100A",
  "brand-beige-1000",
  "brand-beige-900",
  "brand-beige-800",
  "brand-beige-700",
  "brand-beige-600",
  "brand-beige-500",
  "brand-beige-400",
  "brand-beige-300",
  "brand-beige-200",
  "brand-beige-100",
  "brand-magenta-400A",
  "brand-magenta-300A",
  "brand-magenta-200A",
  "brand-magenta-100A",
  "brand-magenta-1000",
  "brand-magenta-900",
  "brand-magenta-800",
  "brand-magenta-700",
  "brand-magenta-600",
  "brand-magenta-500",
  "brand-magenta-400",
  "brand-magenta-300",
  "brand-magenta-200",
  "brand-magenta-100",
  "info-400A",
  "info-300A",
  "info-200A",
  "info-100A",
  "info-1000",
  "info-900",
  "info-800",
  "info-700",
  "info-600",
  "info-500",
  "info-400",
  "info-300",
  "info-200",
  "info-100",
  "danger-400A",
  "danger-300A",
  "danger-200A",
  "danger-100A",
  "danger-1000",
  "danger-900",
  "danger-800",
  "danger-700",
  "danger-600",
  "danger-500",
  "danger-400",
  "danger-300",
  "danger-200",
  "danger-100",
  "warning-400A",
  "warning-300A",
  "warning-200A",
  "warning-100A",
  "warning-1000",
  "warning-900",
  "warning-800",
  "warning-700",
  "warning-600",
  "warning-500",
  "warning-400",
  "warning-300",
  "warning-200",
  "warning-100",
  "success-400A",
  "success-300A",
  "success-200A",
  "success-100A",
  "success-1000",
  "success-900",
  "success-800",
  "success-700",
  "success-600",
  "success-500",
  "success-400",
  "success-300",
  "success-200",
  "success-100",
  "accent-400A",
  "accent-300A",
  "accent-200A",
  "accent-100A",
  "accent-1000",
  "accent-900",
  "accent-800",
  "accent-700",
  "accent-600",
  "accent-500",
  "accent-400",
  "accent-300",
  "accent-200",
  "accent-100",
  "neutral-400A",
  "neutral-300A",
  "neutral-200A",
  "neutral-100A",
  "neutral-000",
  "neutral-1000",
  "neutral-900",
  "neutral-800",
  "neutral-700",
  "neutral-600",
  "neutral-500",
  "neutral-400",
  "neutral-300",
  "neutral-200",
  "neutral-100",
  "bg-overlay",
  "bg-input",
  "bg-default",
  "text-logo",
  "border-focus",
  "bg-sunken",
  "bg-raised",
  "border-meta-lime-strong",
  "border-meta-lime-subtleA",
  "border-meta-lime-subtle",
  "border-meta-lime",
  "border-meta-purple-strong",
  "border-meta-purple-subtleA",
  "border-meta-purple-subtle",
  "border-meta-purple",
  "border-brand-blue-strong",
  "border-brand-blue-subtleA",
  "border-brand-blue-subtle",
  "border-brand-blue",
  "border-brand-beige-strong",
  "border-brand-beige-subtleA",
  "border-brand-beige-subtle",
  "border-brand-beige",
  "border-brand-magenta-strong",
  "border-brand-magenta-subtleA",
  "border-brand-magenta-subtle",
  "border-brand-magenta",
  "border-info-strong",
  "border-info-subtleA",
  "border-info-subtle",
  "border-info",
  "border-danger-strong",
  "border-danger-subtleA",
  "border-danger-subtle",
  "border-danger",
  "border-warning-strong",
  "border-warning-subtleA",
  "border-warning-subtle",
  "border-warning",
  "border-success-strong",
  "border-success-subtleA",
  "border-success-subtle",
  "border-success",
  "border-accent-strong",
  "border-accent-subtleA",
  "border-accent-subtle",
  "border-accent",
  "border-neutral-strong",
  "border-neutral-subtleA",
  "border-neutral-subtle",
  "border-neutral",
  "text-meta-lime-contrast",
  "text-meta-lime-decoration",
  "text-meta-lime-subtle",
  "text-meta-lime",
  "text-meta-purple-contrast",
  "text-meta-purple-decoration",
  "text-meta-purple-subtle",
  "text-meta-purple",
  "text-brand-blue-contrast",
  "text-brand-blue-decoration",
  "text-brand-blue-subtle",
  "text-brand-blue",
  "text-brand-beige-contrast",
  "text-brand-beige-decoration",
  "text-brand-beige-subtle",
  "text-brand-beige",
  "text-brand-magenta-contrast",
  "text-brand-magenta-decoration",
  "text-brand-magenta-subtle",
  "text-brand-magenta",
  "text-info-contrast",
  "text-info-decoration",
  "text-info-subtle",
  "text-info",
  "text-danger-contrast",
  "text-danger-decoration",
  "text-danger-subtle",
  "text-danger",
  "text-warning-contrast",
  "text-warning-decoration",
  "text-warning-subtle",
  "text-warning",
  "text-success-contrast",
  "text-success-decoration",
  "text-success-subtle",
  "text-success",
  "text-accent-contrast",
  "text-accent-decoration",
  "text-accent-subtle",
  "text-accent",
  "text-neutral-contrast",
  "text-neutral-decoration",
  "text-neutral-subtle",
  "text-neutral",
  "bg-meta-lime-strong-pressed",
  "bg-meta-lime-strong-hover",
  "bg-meta-lime-strong",
  "bg-meta-lime-moderate-pressedA",
  "bg-meta-lime-moderate-pressed",
  "bg-meta-lime-moderate-hoverA",
  "bg-meta-lime-moderate-hover",
  "bg-meta-lime-moderateA",
  "bg-meta-lime-moderate",
  "bg-meta-lime-softA",
  "bg-meta-lime-soft",
  "bg-meta-purple-strong-pressed",
  "bg-meta-purple-strong-hover",
  "bg-meta-purple-strong",
  "bg-meta-purple-moderate-pressedA",
  "bg-meta-purple-moderate-pressed",
  "bg-meta-purple-moderate-hoverA",
  "bg-meta-purple-moderate-hover",
  "bg-meta-purple-moderateA",
  "bg-meta-purple-moderate",
  "bg-meta-purple-softA",
  "bg-meta-purple-soft",
  "bg-brand-blue-strong-pressed",
  "bg-brand-blue-strong-hover",
  "bg-brand-blue-strong",
  "bg-brand-blue-moderate-pressedA",
  "bg-brand-blue-moderate-pressed",
  "bg-brand-blue-moderate-hoverA",
  "bg-brand-blue-moderate-hover",
  "bg-brand-blue-moderateA",
  "bg-brand-blue-moderate",
  "bg-brand-blue-softA",
  "bg-brand-blue-soft",
  "bg-brand-beige-strong-pressed",
  "bg-brand-beige-strong-hover",
  "bg-brand-beige-strong",
  "bg-brand-beige-moderate-pressedA",
  "bg-brand-beige-moderate-pressed",
  "bg-brand-beige-moderate-hoverA",
  "bg-brand-beige-moderate-hover",
  "bg-brand-beige-moderateA",
  "bg-brand-beige-moderate",
  "bg-brand-beige-softA",
  "bg-brand-beige-soft",
  "bg-brand-magenta-strong-pressed",
  "bg-brand-magenta-strong-hover",
  "bg-brand-magenta-strong",
  "bg-brand-magenta-moderate-pressedA",
  "bg-brand-magenta-moderate-pressed",
  "bg-brand-magenta-moderate-hoverA",
  "bg-brand-magenta-moderate-hover",
  "bg-brand-magenta-moderateA",
  "bg-brand-magenta-moderate",
  "bg-brand-magenta-softA",
  "bg-brand-magenta-soft",
  "bg-info-strong-pressed",
  "bg-info-strong-hover",
  "bg-info-strong",
  "bg-info-moderate-pressedA",
  "bg-info-moderate-pressed",
  "bg-info-moderate-hoverA",
  "bg-info-moderate-hover",
  "bg-info-moderateA",
  "bg-info-moderate",
  "bg-info-softA",
  "bg-info-soft",
  "bg-danger-strong-pressed",
  "bg-danger-strong-hover",
  "bg-danger-strong",
  "bg-danger-moderate-pressedA",
  "bg-danger-moderate-pressed",
  "bg-danger-moderate-hoverA",
  "bg-danger-moderate-hover",
  "bg-danger-moderateA",
  "bg-danger-moderate",
  "bg-danger-softA",
  "bg-danger-soft",
  "bg-warning-strong-pressed",
  "bg-warning-strong-hover",
  "bg-warning-strong",
  "bg-warning-moderate-pressedA",
  "bg-warning-moderate-pressed",
  "bg-warning-moderate-hoverA",
  "bg-warning-moderate-hover",
  "bg-warning-moderateA",
  "bg-warning-moderate",
  "bg-warning-softA",
  "bg-warning-soft",
  "bg-success-strong-pressed",
  "bg-success-strong-hover",
  "bg-success-strong",
  "bg-success-moderate-pressedA",
  "bg-success-moderate-pressed",
  "bg-success-moderate-hoverA",
  "bg-success-moderate-hover",
  "bg-success-moderateA",
  "bg-success-moderate",
  "bg-success-softA",
  "bg-success-soft",
  "bg-accent-strong-pressed",
  "bg-accent-strong-hover",
  "bg-accent-strong",
  "bg-accent-moderate-pressedA",
  "bg-accent-moderate-pressed",
  "bg-accent-moderate-hoverA",
  "bg-accent-moderate-hover",
  "bg-accent-moderateA",
  "bg-accent-moderate",
  "bg-accent-softA",
  "bg-accent-soft",
  "bg-neutral-strong-pressed",
  "bg-neutral-strong-hover",
  "bg-neutral-strong",
  "bg-neutral-moderate-pressedA",
  "bg-neutral-moderate-pressed",
  "bg-neutral-moderate-hoverA",
  "bg-neutral-moderate-hover",
  "bg-neutral-moderateA",
  "bg-neutral-moderate",
  "bg-neutral-softA",
  "bg-neutral-soft",
];

type TokensWithTailwindTag = Record<string, string | null>;

/**
 * Key: Name
 * Value: Tailwind-name
 */
const newTokensWithoutRegex: TokensWithTailwindTag = {
  ...colors.reduce((acc, token) => {
    acc[token] = generateBgTwTags(token, true);
    return acc;
  }, {} as TokensWithTailwindTag),

  "opacity-disabled": "opacity-ax-disabled",
  "shadow-dialog": "shadow-ax-dialog",
  "font-weight-regular": "font-ax-regular",
  "font-weight-bold": "font-ax-bold",
  "font-size-small": "text-ax-small",
  "font-size-medium": "text-ax-medium",
  "font-size-large": "text-ax-large",
  "font-size-xlarge": "text-ax-xlarge",
  "font-size-heading-xsmall": "text-ax-heading-xsmall",
  "font-size-heading-small": "text-ax-heading-small",
  "font-size-heading-medium": "text-ax-heading-medium",
  "font-size-heading-large": "text-ax-heading-large",
  "font-size-heading-xlarge": "text-ax-heading-xlarge",
  "font-size-heading-2xlarge": "text-ax-heading-2xlarge",
  "font-line-height-medium": "leading-ax-medium",
  "font-line-height-large": "leading-ax-large",
  "font-line-height-xlarge": "leading-ax-xlarge",
  "font-line-height-heading-xsmall": "leading-ax-heading-xsmall",
  "font-line-height-heading-small": "leading-ax-heading-small",
  "font-line-height-heading-medium": "leading-ax-heading-medium",
  "font-line-height-heading-large": "leading-ax-heading-large",
  "font-line-height-heading-xlarge": "leading-ax-heading-xlarge",
  "font-line-height-heading-2xlarge": "leading-ax-heading-2xlarge",
  "font-family": "font-font-family",
  "breakpoint-2xl-down": null,
  "breakpoint-2xl": "ax-2xl",
  "breakpoint-xl-down": null,
  "breakpoint-xl": "ax-xl",
  "breakpoint-lg-down": null,
  "breakpoint-lg": "ax-lg",
  "breakpoint-md-down": null,
  "breakpoint-md": "ax-md",
  "breakpoint-sm-down": null,
  "breakpoint-sm": "ax-sm",
  "breakpoint-xs": null,
  "radius-full": generateRoundedTwTags("full"),
  "radius-12": generateRoundedTwTags("12"),
  "radius-8": generateRoundedTwTags("8"),
  "radius-4": generateRoundedTwTags("4"),
  "radius-2": generateRoundedTwTags("2"),
  "space-128": null,
  "space-96": null,
  "space-80": null,
  "space-72": null,
  "space-64": null,
  "space-56": null,
  "space-48": null,
  "space-44": null,
  "space-40": null,
  "space-36": null,
  "space-32": null,
  "space-28": null,
  "space-24": null,
  "space-20": null,
  "space-16": null,
  "space-12": null,
  "space-8": null,
  "space-6": null,
  "space-4": null,
  "space-2": null,
  "space-1": null,
  "space-0": null,
};

type TokensWithRegexes = Record<
  string,
  { tw: string; regexes: ReturnType<typeof getFrameworkRegexes> }
>;

const v8TokenConfig: TokensWithRegexes = Object.entries(
  newTokensWithoutRegex,
).reduce((acc, [name, tw]) => {
  acc[name] = {
    tw,
    regexes: getFrameworkRegexes({
      legacy: false,
      token: `--ax-${name}`,
      twString: tw,
    }),
  };
  return acc;
}, {} as TokensWithRegexes);

export { v8TokenConfig };
