/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Union of every `name` declared in a `*.meta.ts` file. Regenerated by
 * `scripts/extract-metadata.ts` (runs as part of `yarn docgen`). Used to type
 * `ComponentMetadata.related` so a reference to a non-existent component fails
 * type-checking.
 */
export type ComponentName = "Accordion";
