/**
 * AUTO-GENERATED — do not edit by hand.
 *
 * Union of every `name` declared in a `*.meta.ts` file. Regenerated by
 * `scripts/metadata/generate-component-names.ts` (via lint-staged and
 * `yarn docgen`). Used to type `ComponentMetadata.related` so a reference to a
 * non-existent component fails type-checking.
 */
export type ComponentName = "Accordion";
