apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aksel-website-v7
  namespace: designsystem
  labels:
    team: designsystem
spec:
  image: {{ image }}
  port: 3000
  ingresses:
    - "https://aksel-v7.nav.no"
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 50m
      memory: 400Mi
  liveness:
    path: /api/isAlive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /api/isAlive
    initialDelay: 20
    timeout: 1
  accessPolicy:
    outbound:
      external:
        - host: raw.githubusercontent.com
      rules: []