name: "SPA Deploy Action"
description: "Upload Single Page Application (SPA) to CDN and deploy to NAIS"
inputs:
  team:
    description: "Team name"
    required: true
  app:
    description: "Application name"
    required: true
  source:
    description: "Application source directory"
    required: true
  environment:
    description: "Environment name"
    required: true
  tenant:
    description: "Tenant slug"
    default: "nav"
    required: true
  ingress:
    description: "Application ingress URL"
    required: true
  ingressClass:
    description: "Ingress class"
    required: false
    default: ""
  project_id:
    description: "Google Cloud project ID where buckets are hosted"
    required: false
  identity_provider:
    description: "Google Workload Identity Provider"
    required: false
  cache_invalidation:
    description: "Cache invalidation"
    required: false
    default: "false"

outputs:
  url:
    description: "SPA URL"
    value: ${{ inputs.ingress }}

runs:
  using: "composite"
  steps:
    - id: setup
      name: Setup for SPA deploy
      uses: nais/deploy/actions/spa-setup-task@master
      with:
        tenant: ${{ inputs.tenant }}
        team-name: ${{ inputs.team }}
        app-name: ${{ inputs.app }}
        ingress: ${{ inputs.ingress }}
        ingressClass: ${{ inputs.ingressClass }}
        environment: ${{ inputs.environment }}

    - id: cdn-upload
      name: Upload SPA to CDN
      uses: nais/deploy/actions/cdn-upload/v2@master
      with:
        team: ${{ inputs.team }}
        tenant: ${{ inputs.tenant }}
        source: ${{ inputs.source }}
        source_keep_parent_name: false
        destination: ${{ steps.setup.outputs.cdn-destination }}
        project_id: ${{ inputs.project_id }}
        identity_provider: ${{ inputs.identity_provider }}
        cache_invalidation: ${{ inputs.cache_invalidation == 'true' }}

    - id: nais-deploy
      name: Deploy SPA to NAIS
      uses: nais/deploy/actions/deploy@v2
      env:
        CLUSTER: ${{ steps.setup.outputs.nais-cluster }}
        RESOURCE: ${{ steps.setup.outputs.nais-resource }}
        TEAM: ${{ inputs.team }}
