apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: update-views-job
  namespace: designsystem
  labels:
    team: designsystem
spec:
  image: {{ image }}
  schedule: "0 * * * *"
  command: 
    - deno
    - run
    - --allow-net
    - --allow-env
    - --allow-read
    - scripts/article-views/update-article-views/main.ts
  restartPolicy: Never
  accessPolicy:
    outbound:
      external:
        - host: hnbe3yhs.api.sanity.io
        - host: reops-proxy.intern.nav.no