name: Backup Sanity dataset

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */3 * *"

permissions:
  contents: read

jobs:
  execute:
    name: Export and upload Sanity backup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: yarn
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies
        run: cd aksel.nav.no/sanity-studio && yarn
        env:
          NPM_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Export dataset
        run: cd aksel.nav.no/sanity-studio && yarn sanity:backup
        env:
          SANITY_READ: ${{ secrets.SANITY_READ }}

      - name: Authenticate with GCP
        uses: "google-github-actions/auth@v3"
        with:
          credentials_json: "${{ secrets.gcp_credentials_prod }}"

      - name: Upload backup to GCS bucket
        uses: "google-github-actions/upload-cloud-storage@v3"
        with:
          path: ./aksel.nav.no/sanity-studio
          destination: "aksel-website-prod/backups"
          glob: "backup-*.tar.gz"
