name: Cleanup E2E Docker images

on:
  schedule:
    - cron: "0 4 * * 1"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package-name:
          - aksel-e2e
    steps:
      - name: Delete old container images
        uses: actions/delete-package-versions@e5bc658cc4c965c472efe991f8beea3981499c55 # actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.package-name }}
          package-type: container
          delete-only-untagged-versions: false
          min-versions-to-keep: 1
          token: ${{ secrets.GITHUB_TOKEN }}
