name: Deploy Aksel MCP server

on:
  push:
    branches:
      - main
    paths:
      - "mcp-server/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE: ghcr.io/navikt/aksel

jobs:
  build_and_deploy:
    name: Build and deploy to prod-gcp
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          npm_auth_token: ${{ secrets.READER_TOKEN }}

      - name: Test mcp-server
        run: cd mcp-server && yarn test

      - name: Build mcp-server
        run: cd mcp-server && yarn build

      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: designsystem
          dockerfile: mcp-server/Dockerfile
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: mcp-server/.nais/app.yaml
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
