name: E2E / Playwright Tests
on:
  push:
    branches: [main, next]
    paths:
      - "aksel.nav.no/**"
  pull_request:
    branches: [main, next]
    paths:
      - "aksel.nav.no/**"

jobs:
  playwright:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-jammy

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup and build Next.js application
        uses: ./.github/actions/build-website
        with:
          use_cdn_assets: false
          npm_auth_token: ${{ secrets.READER_TOKEN }}
          nais_id_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          nais_project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          sanity_read_token: ${{ secrets.SANITY_READ }}
          sanity_read_no_drafts_token: ${{ secrets.SANITY_READ_NO_DRAFTS }}

      - name: Run Playwright tests
        env:
          SANITY_READ: ${{ secrets.SANITY_READ }}
          SANITY_READ_NO_DRAFTS: ${{ secrets.SANITY_READ_NO_DRAFTS }}

        run: yarn workspace website e2e:ci-full
