name: Deploy referansesider SPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup project
        uses: ./.github/actions/setup
        with:
          npm_auth_token: ${{ secrets.READER_TOKEN }}

      - run: cd ./examples/referansesider && yarn && yarn build
      - uses: nais/deploy/actions/spa-deploy/v2@master
        with:
          app: aksel-referansesider
          team: designsystem
          source: ./examples/referansesider/dist
          ingress: https://aksel-referansesider.ansatt.dev.nav.no
          environment: dev
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          cache_invalidation: true
