name: Update article views (Naisjob)

on:
  workflow_dispatch:

jobs:
  execute:
    name: Build and deploy article views job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
      - name: Build and push Docker image
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: designsystem
          push_image: true
          dockerfile: scripts/deno/article-views/Dockerfile.update-article-views
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Deploy Naisjob to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: scripts/deno/article-views/nais-update-views-job.yml
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
